# Generated by Django 6.0.1 on 2026-02-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_verse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosectionslider',
            name='link',
            field=models.CharField(max_length=255),
        ),
    ]
