# Generated by Django 6.0.1 on 2026-02-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_verse', '0002_alter_herosectionslider_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosectionslider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='herosectionslider',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
