# Generated by Django 6.0.1 on 2026-02-09 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_verse', '0003_herosectionslider_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anime_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'anime',
            },
        ),
        migrations.CreateModel(
            name='AnimeWorld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('link', models.CharField(max_length=255)),
                ('img_src', models.ImageField(upload_to='anime/covers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('anime_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anime_world', to='anime_verse.anime')),
            ],
        ),
    ]
