# Generated by Django 6.0.1 on 2026-02-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_verse', '0005_anime_created_at_anime_is_active_anime_is_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'blog_filter',
            },
        ),
        migrations.AlterModelTable(
            name='animeworld',
            table='anime_world',
        ),
    ]
