# Generated by Django 6.0.1 on 2026-02-10 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_verse', '0006_blogfilter_alter_animeworld_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogfilter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blogfilter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogfilter',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
