# Generated by Django 6.0.1 on 2026-02-12 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_verse', '0007_blogfilter_created_at_blogfilter_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeworld',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
    ]
