# Generated by Django 6.0.1 on 2026-02-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_verse', '0009_category_animeworld_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSideBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img_src', models.ImageField(upload_to='banners/sidebar')),
                ('link', models.URLField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'homepage_side_banner',
            },
        ),
        migrations.AlterField(
            model_name='animeworld',
            name='link',
            field=models.URLField(max_length=255),
        ),
    ]
