# Generated by Django 6.0.1 on 2026-02-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_verse', '0010_homepagesidebanner_alter_animeworld_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesidebanner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
