# Generated by Django 6.0.1 on 2026-02-12 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_verse', '0012_homepagevideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcommingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('img_src', models.ImageField(upload_to='banners/upcomming-events')),
                ('link', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('anime_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upcomming_event', to='anime_verse.anime')),
            ],
            options={
                'db_table': 'upcomming_event',
            },
        ),
    ]
