# Generated by Django 6.0.1 on 2026-02-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_verse', '0014_subscribecomic'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeworld',
            name='comics',
            field=models.FileField(null=True, upload_to='anime/comics'),
        ),
    ]
