# Generated by Django 6.0.1 on 2026-02-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_verse', '0017_userprofile_delete_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Prefer not to say')], max_length=1, null=True),
        ),
    ]
