# Generated by Django 6.0.1 on 2026-02-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_verse', '0018_alter_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img_src', models.ImageField(upload_to='default_profiles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'default_profiles',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='img_src',
            field=models.ImageField(blank=True, null=True, upload_to='users/profiles'),
        ),
    ]
