# Generated by Django 6.0.1 on 2026-02-18 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_verse', '0019_defaultprofile_alter_userprofile_img_src'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='defaultprofile',
            table=None,
        ),
    ]
