# Generated by Django 6.0.1 on 2026-02-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_verse', '0022_userprofile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, choices=[('India', 'India'), ('Japan', 'Japan'), ('USA', 'USA'), ('Canada', 'Canada'), ('UK', 'UK'), ('Germany', 'Germany'), ('France', 'France')], default='', max_length=100),
        ),
    ]
