# Generated by Django 6.0.1 on 2026-02-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_verse', '0024_animeworld_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeworld',
            name='link',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
