# Generated by Django 6.0.1 on 2026-02-23 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_verse', '0025_alter_animeworld_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animeworld',
            name='link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
